# 2 Models:
- Keras Classifier: great speed, perfect accuracy, passed baselines on first try
- KNN: very poor performance

In [1]:
import pandas as pd

In [14]:
train = pd.read_csv('/Users/andriylunin/Desktop/P11/voice_forensics_train.csv').drop(columns = ['Id','speaker_id','age'])
test = pd.read_csv('voice2genderage_test_x.csv').drop(columns = ['Id'])
train

,gender,d1,d2,d3,d4,d5,d6,d7,d8,d9,...,d119,d120,d121,d122,d123,d124,d125,d126,d127,d128
0,female,-0.192353,-0.113325,0.076270,-0.025666,0.065720,-0.138643,0.060215,0.025906,-0.182360,...,0.004161,0.081468,-0.049854,-0.086956,-0.229366,0.081781,-0.102319,-0.015848,-0.165077,0.072695
1,female,0.012671,-0.020054,-0.080550,-0.066981,-0.023068,0.021807,0.109370,0.091685,0.016260,...,0.070559,0.124623,0.042512,-0.147252,0.068138,0.148022,-0.073004,-0.174536,-0.090798,-0.089854
2,female,0.211005,-0.091166,-0.204517,-0.014342,0.156766,-0.062494,0.136877,-0.087067,-0.057684,...,0.059373,-0.051881,-0.039299,-0.171386,0.066677,0.129493,-0.169326,-0.052836,-0.100826,-0.097579
3,female,-0.093959,-0.181139,0.072483,0.055215,0.046015,-0.152144,0.123068,0.003379,-0.148498,...,-0.008471,0.026831,-0.063509,-0.168682,-0.137628,0.096271,-0.109646,0.036716,-0.198027,0.030743
4,female,-0.123451,-0.140431,0.049797,-0.083786,-0.067806,0.017086,0.155579,0.060626,-0.145429,...,-0.098829,0.037679,0.105494,0.014183,-0.011838,0.053571,0.031440,-0.030806,-0.126419,-0.033699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28307,male,-0.037807,-0.133849,0.143385,0.086811,0.097597,0.073502,0.125016,0.051362,-0.203169,...,0.095744,0.054801,0.055865,0.093116,0.003893,0.212841,-0.003783,-0.021877,-0.181550,-0.142920
28308,male,-0.122795,-0.100314,0.042107,0.032400,-0.014548,0.033853,0.164863,-0.032684,-0.225691,...,0.102636,0.065473,0.130178,0.017921,0.018958,-0.064648,0.052969,-0.153364,-0.090209,-0.030031
28309,male,-0.083391,-0.089955,0.088400,0.102962,0.028494,0.103521,0.141444,-0.121890,-0.218195,...,0.097971,0.070337,0.104931,0.000222,-0.044901,0.027303,0.055895,-0.123488,-0.147937,0.049761
28310,male,0.004497,-0.141346,0.039395,0.050399,-0.005776,0.082760,0.090685,0.001032,-0.252312,...,0.051226,0.055620,0.129208,-0.066527,0.011709,0.086845,-0.035429,-0.074938,-0.129237,-0.045822
28311,male,-0.124237,-0.074758,0.039934,0.118177,-0.008744,0.012284,0.196901,0.020655,-0.257089,...,0.051417,0.014536,0.079638,-0.068271,-0.032578,0.034618,-0.063832,-0.058114,-0.110376,0.077546

In [12]:
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils

# for modeling
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.callbacks import EarlyStopping

In [60]:
df = train
df['gender'].replace(('male', 'female'), (0, 1), inplace=True)
df

,gender,d1,d2,d3,d4,d5,d6,d7,d8,d9,...,d119,d120,d121,d122,d123,d124,d125,d126,d127,d128
0,1,-0.192353,-0.113325,0.076270,-0.025666,0.065720,-0.138643,0.060215,0.025906,-0.182360,...,0.004161,0.081468,-0.049854,-0.086956,-0.229366,0.081781,-0.102319,-0.015848,-0.165077,0.072695
1,1,0.012671,-0.020054,-0.080550,-0.066981,-0.023068,0.021807,0.109370,0.091685,0.016260,...,0.070559,0.124623,0.042512,-0.147252,0.068138,0.148022,-0.073004,-0.174536,-0.090798,-0.089854
2,1,0.211005,-0.091166,-0.204517,-0.014342,0.156766,-0.062494,0.136877,-0.087067,-0.057684,...,0.059373,-0.051881,-0.039299,-0.171386,0.066677,0.129493,-0.169326,-0.052836,-0.100826,-0.097579
3,1,-0.093959,-0.181139,0.072483,0.055215,0.046015,-0.152144,0.123068,0.003379,-0.148498,...,-0.008471,0.026831,-0.063509,-0.168682,-0.137628,0.096271,-0.109646,0.036716,-0.198027,0.030743
4,1,-0.123451,-0.140431,0.049797,-0.083786,-0.067806,0.017086,0.155579,0.060626,-0.145429,...,-0.098829,0.037679,0.105494,0.014183,-0.011838,0.053571,0.031440,-0.030806,-0.126419,-0.033699
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
28307,0,-0.037807,-0.133849,0.143385,0.086811,0.097597,0.073502,0.125016,0.051362,-0.203169,...,0.095744,0.054801,0.055865,0.093116,0.003893,0.212841,-0.003783,-0.021877,-0.181550,-0.142920
28308,0,-0.122795,-0.100314,0.042107,0.032400,-0.014548,0.033853,0.164863,-0.032684,-0.225691,...,0.102636,0.065473,0.130178,0.017921,0.018958,-0.064648,0.052969,-0.153364,-0.090209,-0.030031
28309,0,-0.083391,-0.089955,0.088400,0.102962,0.028494,0.103521,0.141444,-0.121890,-0.218195,...,0.097971,0.070337,0.104931,0.000222,-0.044901,0.027303,0.055895,-0.123488,-0.147937,0.049761
28310,0,0.004497,-0.141346,0.039395,0.050399,-0.005776,0.082760,0.090685,0.001032,-0.252312,...,0.051226,0.055620,0.129208,-0.066527,0.011709,0.086845,-0.035429,-0.074938,-0.129237,-0.045822
28311,0,-0.124237,-0.074758,0.039934,0.118177,-0.008744,0.012284,0.196901,0.020655,-0.257089,...,0.051417,0.014536,0.079638,-0.068271,-0.032578,0.034618,-0.063832,-0.058114,-0.110376,0.077546

In [16]:
df.gender.value_counts()

1    16568
0    11744
Name: gender, dtype: int64

In [19]:
import numpy as np
Y = df['gender']
X = df.drop(['gender'], axis=1)

print(X.shape)
print(Y.shape)
X = np.array(X)

(28312, 128)
(28312,)

In [65]:
# build a model
model = Sequential()
model.add(Dense(32, input_shape=(X.shape[1],), activation='relu')) # Add an input shape! (features,)
model.add(Dense(32, activation='relu'))
model.add(Dense(1, activation='sigmoid'))
model.summary()

# compile the model
model.compile(optimizer='Adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])


es = EarlyStopping(monitor='val_accuracy',
                                   mode='max',
                                   patience=15,
                                   restore_best_weights=True)


history = model.fit(X,
                    Y,
                    callbacks=[es],
                    epochs=10,
                    batch_size=10,
                    validation_split=0.2,
                    shuffle=True,
                    verbose=1)

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_15 (Dense)            (None, 32)                4128

 dense_16 (Dense)            (None, 32)                1056

 dense_17 (Dense)            (None, 1)                 33

=================================================================
Total params: 5,217
Trainable params: 5,217
Non-trainable params: 0
_________________________________________________________________
Epoch 1/10
2265/2265 [==============================] - 4s 2ms/step - loss: 0.2186 - accuracy: 0.9270 - val_loss: 0.1764 - val_accuracy: 0.9518
Epoch 2/10
2265/2265 [==============================] - 4s 2ms/step - loss: 0.1576 - accuracy: 0.9563 - val_loss: 0.1657 - val_accuracy: 0.9557
Epoch 3/10
2265/2265 [==============================] - 4s 2ms/step - loss: 0.1442 - accuracy: 0.9618 - val_loss: 0.1621 - val_accuracy: 0.9574
Epoch 4/10
2265/2265 [==============================] - 4s 2ms/step - loss: 0.1337 - accuracy: 0.9646 - val_loss: 0.1603 - val_accuracy: 0.9578
Epoch 5/10
2265/2265 [==============================] - 4s 2ms/step - loss: 0.1267 - accuracy: 0.9662 - val_loss: 0.1648 - val_accuracy: 0.9553
Epoch 6/10
2265/2265 [==============================] - 4s 2ms/step - loss: 0.1218 - accuracy: 0.9672 - val_loss: 0.1642 - val_accuracy: 0.9576
Epoch 7/10
2265/2265 [==============================] - 4s 2ms/step - loss: 0.1167 - accuracy: 0.9684 - val_loss: 0.1757 - val_accuracy: 0.9523
Epoch 8/10
2265/2265 [==============================] - 4s 2ms/step - loss: 0.1122 - accuracy: 0.9694 - val_loss: 0.1706 - val_accuracy: 0.9553
Epoch 9/10
2265/2265 [==============================] - 4s 2ms/step - loss: 0.1077 - accuracy: 0.9691 - val_loss: 0.1754 - val_accuracy: 0.9574
Epoch 10/10
2265/2265 [==============================] - 5s 2ms/step - loss: 0.1031 - accuracy: 0.9709 - val_loss: 0.1765 - val_accuracy: 0.9576

In [66]:
x_test = np.array(test)

In [67]:
np.round(model.predict(x_test),0)

array([[1.],
       [1.],
       [1.],
       ...,
       [1.],
       [1.],
       [1.]], dtype=float32)

In [68]:
ans = pd.read_csv('voice2gender_solution_sample.csv')
ans

        Id Predicted
0        0    female
1        1      male
2        2    female
3        3      male
4        4    female
...    ...       ...
8797  8797      male
8798  8798    female
8799  8799      male
8800  8800    female
8801  8801      male

[8802 rows x 2 columns]

In [69]:
ans['Predicted'] = np.round(model.predict(x_test),0)

In [70]:
ans['Predicted'].replace((0, 1),('male', 'female'), inplace=True)

In [71]:
ans.to_csv('atempt1.csv',index = False)

In [72]:
ans

        Id Predicted
0        0    female
1        1    female
2        2    female
3        3    female
4        4    female
...    ...       ...
8797  8797    female
8798  8798    female
8799  8799    female
8800  8800    female
8801  8801    female

[8802 rows x 2 columns]

In [ ]:
from sklearn.svm import SVC

train = pd.read_csv('/Users/andriylunin/Desktop/P11/voice_forensics_train.csv').drop(columns = ['Id','speaker_id','age'])
test = pd.read_csv('voice2genderage_test_x.csv').drop(columns = ['Id'])


Y = df['gender']
X = df.drop(['gender'], axis=1)


linear_svc = LinearSVC(C=15, max_iter=10 ** 5)
linear_svc.fit(X, y)

test_X = test.drop("Id", axis=1)
test_Y = pd.DataFrame(test["Id"])

test_Y["Predicted"] = linear_svc.predict(test_X)
test_Y.to_csv("speak_id_Att4.csv", index=False)